### ISSUE TITLE
Referencing VBCCR13 or VBCCR15 from VB.net error

### ISSUE THREAD

**Issue by melanysoft** [Kr00l/VBCCR#1]
Hi Krool, I'd like to thank you and express my respect to the project you have built and maintain.
Your controls are great and stable so I implemented some of them my software product in Serbia. If there is something you need help with, I'd be glad to do that (if capable :)

As for the issue, it's about referencing the VBCCR library (or any of user-controls built using VBCCR components) from VB.net (tried versions 2013-2017).

VB.net interops with ActiveX controls making a wrapper automatically. It works for MSHFlex, my own VB6 built user controls, and some other controls I've tried. But when referencing VBCCR13.ocx (or VBCCR15.ocx) following warning errors occur preventing Vb.net to build the wrapper:

```
1.Error loading type library/dll (TYPE_E_CONTLOADLIBRARY) - 0x80029C4A
2.Could not determine the dependencies of the COM reference "VBCCR15". Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY))			
3.Could not determine the dependencies of the COM reference "VBRUN". Type mismatch. (Exception from HRESULT: 0x8002802A (TYPE_E_WRONGTYPEKIND))
4.The referenced component 'VBCCR15' could not be found.
```

Now, I must mention that the component is registered correctly and fully functional from within VB6.

**Note**
1. The same happens when loading with OleView's "TypeLib Viewer"
2. The **VBCCR10** can be viewd with "TypeLib Viewer", still can't be referenced from .Net, but with only one error - the Could not determine the dependencies of the COM reference "VBRUN" (No.3).

The question is, do you have any idea, or some advice what should I do, or where to start looking in the source code to help resolve this issue, and make VBCCR referable from within VB.net ?

Thanks andd best regards,

Milan

**Comment by Kr00l** [comment]
Thanks for your report. VBRUN is used in dome enums and object types and accessible public interface wise.
The error in txpe lib. I don't know. Have you installed OLEGuids.tlb ? Normally it's not needed as it gets compiled into and there is no public declaration from it. But who k ows maybe .net has problems.
I just can confirm that office vba will run it. What .net complains don't know.

**Comment by melanysoft** [comment]
Thanks Krool, I'll investigate more and try to find a fix. I'm trying with VBCCR15,and yes, I did install OLEGuids.tlb. Ill post you the fix if/when I find it :)

**Comment by Kr00l** [comment]
Thanks so far.

Public Property Get Value(Optional ByVal Modifiers As VBRUN.ShiftConstants) As VBRUN.KeyCodeConstants

It is intended that Modifiers is ByRef and not ByVal. Can you please try if 'ByRef Modifiers As Integer' will also fix the issue?

Suggested new definitions to be tested:

Public Property Get Value(Optional ByRef Modifiers As Integer) As VBRUN.KeyCodeConstants

and

Public Property Let Value(Optional ByRef Modifiers As Integer, ByVal NewValue As VBRUN.KeyCodeConstants)

**Comment by melanysoft** [comment]
Hi Krool, sorry for not being able to test the suggested solution before - a busy month I guess.
Anyway, it works when defined as you suggested.

Is this solution going to be implemented in VBCCR15, or do you suggest me to keep this on a private fork ?

Thanks,
BR

**Comment by sohailfayez** [comment]
SSDSD
