### ISSUE TITLE
No Wiki! 

### ISSUE THREAD

**Issue by yereverluvinunclebert** [Kr00l/VBCCR#10]
Please create the VBCCR wiki for all of us to help you create and add documentation.

**Comment by Kr00l** [comment]
I created a wiki 'Migration Guide' here in this github repository. Does it work for you to add content?

**Comment by yereverluvinunclebert** [comment]
I will try!

**Comment by yereverluvinunclebert** [comment]
No it doesn't let me modify it, there must be some configuration thing somewhere that allows me to.

**Comment by yereverluvinunclebert** [comment]
https://help.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

**Comment by Kr00l** [comment]
Ok. Try again

**Comment by yereverluvinunclebert** [comment]
It works! I have added some text to the beginning just to explain the lack of documentation.

I will add some structure as my brain and time allows.
I suggest we have a headline per control and an installation/configuration section that will hopefully be provide by theM..man. I have suggested that he obtain a github account and when he does that you can grant him the same level of access. He can then get going.

As I encounter each of your controls I will add what I learn, the differences &c - so at first the docs will be brief and incomplete. 

Your occasional words will be invaluable/essential, don't worry about format, typos, grammar nor style.

and you can close this issue!
