### ISSUE TITLE
Cannot compile projects.

### ISSUE THREAD

**Issue by cycle40** [Kr00l/VBCCR#11]
When compiling projects. A Compile error  "ByRef Argument Type Mismatch" occurs in a function 'Original_IPPB_GetDisplayString' in 'VtableHandle.bas'.

The function is declared as
Private Function Original_IPPB_GetDisplayString(ByRef This As Long, ByVal DispID As Long, ByRef pDisplayName As Long) As Long

So, 'pDisplayName' is ByRef Long, but it is used to call ShadowIPPB.GetDisplayString which seems to need String.

sorry for my poor english.

**Comment by Kr00l** [comment]
Please update OLEGuids.tlb and try again

**Comment by cycle40** [comment]
Thank you, sir.
Sorry for wasting your precious time.
