### ISSUE TITLE
Runtime Error 713 - Class not registered

### ISSUE THREAD

**Issue by hellblade** [Kr00l/VBCCR#12]
Hey,

I'm looking to use this in an existing project, with the OCX version. I've registered it and have linked it to the project, along with OLEGuids.tlb.

I've updated some of the standard controls to point to the VBCCR16 ones. When I double click on some of the forms in VB6, the RTE 713 comes up, with VBCCR in the warning message title. Likewise when I try to run the application. 

I can't reproduce it with a brand new project though.
So I'm not expecting a resolution, just maybe someone has come across it before or might have any thoughts on what it could be or where to look into it?

**Comment by Kr00l** [comment]
Incompatible frx section. Please check

**Comment by hellblade** [comment]
Ahh, I see, seems to be the pictures - tried in a sample project of having a form with a button, adding a picture to the button then changing the file to have the button be the VBCCR one and that triggers the error.

So I'll just remove the picture property during my conversion process which should fix it.

Thanks!
