### ISSUE TITLE
OptionButtonW Click not raised when Owner Draw mode set

### ISSUE THREAD

**Issue by hellblade** [Kr00l/VBCCR#13]
When an OptionButtonW is set to be OwnerDraw, the Click event isn't being raised. The value still seems to be updating though.

To reproduce:

- Open up the demo app
- Change OptionButtonW2 in Main form to be Owner Drawn. Add a Click hander to update the caption
- Run it and if you click OptionButtonW1, then where OptionButtonW2 is you see OptionButtonW1 is no longer selected but no click event was raised for OptionButtonW2

**Comment by Kr00l** [comment]
Thanks for this. Got fixed!

**Comment by hellblade** [comment]
Thanks for the quick fix!
