### ISSUE TITLE
Feature: Slider OwnerDraw

### ISSUE THREAD

**Issue by hellblade** [Kr00l/VBCCR#14]
Hi,

From the docs it looks like the slider Win32 control would support custom drawing: https://docs.microsoft.com/en-us/windows/win32/controls/nm-customdraw-trackbar

Would it be hard to add OwnerDraw support into the Slider control? Feel free to not do it of course, just would be useful if it's fairly straight forward to add in.

**Comment by Kr00l** [comment]
Thanks. I put it in my todo list.

**Comment by Kr00l** [comment]
DrawMode property now included for the slider control

**Comment by hellblade** [comment]
Awesome, thanks!
