### ISSUE TITLE
RichTextBox - multiline and selection

### ISSUE THREAD

**Issue by hellblade** [Kr00l/VBCCR#15]
There seems to be a bit of an odd behaviour in the RichTextBox compared to the standard one.

.SelStart and .SelLength seem to return indexes based on the text using just a single new line "\n" (vbLf), where as the .Text uses return as well, "\r\n" (vbCrLf).

You can see it in the RichTextBoxForm sample if you add this code:

```
Private Sub RichTextBox1_KeyPress(KeyChar As Integer)
    Debug.Print RichTextBox1.SelStart & " out of: " & Len(RichTextBox1.Text)
End Sub
```

If you run it and just add text to the end of the first line, it's fine they both match up.
But when press enter, it become different by 1, and gets further out for each line break.

**Comment by Kr00l** [comment]
Looks like EM_EXGETSEL behaves different in a v1 RichEdit (MS control for VB6) and the latest version. See http://www.yqcomputer.com/44_492_1.htm
