### ISSUE TITLE
OLE Drop events not working on FrameW

### ISSUE THREAD

**Issue by riksoft** [Kr00l/VBCCR#16]
This problem happens only after compiling an app, not in the IDE. In the IDE it's all OK.
It seems that, differently from an ordinary frame, on a FrameW the events OLEDragDrop and OLEDragOver are not triggered when dropping something.

As a workaround, a picturebox inside the frame does the trick.

**Comment by Kr00l** [comment]
I cannot replicate the bug. Is your FrameW OLEDropMode property set to 1 - Manual and not to 0 - None?

**Comment by riksoft** [comment]
The frame is on 0-none (cannot be different because it gives trying to set 1-manual VB6 get angry with realtime error &H80040101 as soon as I change the option), and the label is on 1-manual.
In the IDE it's OK, the problem it's only **once compiled** : it does absolutely nothing.
Attached an example, both source and exe.

[0-drop.zip](https://github.com/Kr00l/VBCCR/files/5042817/0-drop.zip)

**Comment by Kr00l** [comment]
Thanks. Confirmed.
I updated v130 for VBCCR16.OCX. Can you try again ?

**Comment by riksoft** [comment]
Hi Kr00l,
The ocx 1.6.0.130 seems to have the same problem.
The ocx is 100% binary compatible so at first I've tried simply overwriting the OCX deleting the .oca file. Same problem. So I did this to be sure:
- Changed the tlb with the new one
- Again, copy the ocx over the old one and deleted the .oca
- Unregistered/registered again
- Recompiled the test vbp

In the IDE it works OK as before while the compiled vbp has the same problem of not triggering the OLEDrop event.

**Comment by Kr00l** [comment]
For me it worked in your demo. Please ensure that OLEDropMode is set to 1 - Manual for the FrameW. (At design time or at run-time)

**Comment by riksoft** [comment]
The example doesn't work for me, no matter if oledrop is 0 or 1 on the frameW. It works only modifing the source code, adding the oledrop event on the frameW and that way when I drop on the label it triggers the FrameW event. The oledrop event on the label never occurs.

**Comment by Kr00l** [comment]
I fixed only that FrameW ensures it works for OLEDrop. What I confirm what does not work is the windowless controls. It's a known Vb6 issue with UserControls as control container.
Google for "Q192171: BUG: OLEDragDrop Fails on Contained Windowless Controls".

The resolution is to use a windowed control. (E.g. put a PictureBox and inside a label control).
Or switch back to intrinsic VB.Frame control.
Sorry..

**Comment by Kr00l** [comment]
I will develop a "WindowedLabel" control that works the same as the LabelW control, but can come handy for situations where a windowless control causes problem. (such as this scenario)

**Comment by riksoft** [comment]
No problem Kr00l, mine was more of a feedback than a problem. I had all fixed in the first place using a pictureBox and I left it that way. It was only a feedback just in case you want to mimic the common control as much as possible. By tghe way, in 20 years I think this is the first time I've used a label as an OleDrop target! :-)
