### ISSUE TITLE
ListView.SetFocus() raises an error when ListView.Visible = False

### ISSUE THREAD

**Issue by ipundit** [Kr00l/VBCCR#23]
To reproduce,
1) Put a ListView control on a form
2) Execute this code:

<pre lang="VB6">
ListView.Visible = false
ListView.SetFocus()
</pre>

The bug is in ListView.cls and is pretty simple to fix:

<pre lang="VB6">
Public Sub SetFocus()
+ If Me.Visible then ' Add this if check
    Extender.SetFocus
+ End If
End Sub
</pre>

**Comment by Kr00l** [comment]
The MS ListView also throws an error for ListView.SetFocus() when the control is not visible.

You can do a check in your code.
`If ListView.Visible = True Then ListView.SetFocus()`
