### ISSUE TITLE
IPerPropertyBrowsing implementation has incorrect use of CoTaskMemAlloc (take 2)

### ISSUE THREAD

**Issue by WaynePhillipsEA** [Kr00l/VBCCR#26]
Apologies for the previous incorrect bug report.  Here's the correct one:

In `IPPB_GetPredefinedStrings`, you'll see this:

```
    pCaStringsOut.cElems = cElems
    pCaStringsOut.pElems = pElems
    For nElemCount = 0 To cElems - 1
        lpString = CoTaskMemAlloc(Len(StringsOutArray(nElemCount)) + 1)
        CopyMemory ByVal lpString, StrPtr(StringsOutArray(nElemCount)), 4
        CopyMemory ByVal UnsignedAdd(pElems, nElemCount * 4), ByVal lpString, 4
    Next nElemCount
```

First, note that you haven't copied the content of the string into `lpString`, you've just moved the StrPtr around.  

Ultimately what's actually happening here is that the `pElems` array just gets filled with the direct pointers from `StrPtr(StringsOutArray(nElemCount))`, so you've essentially populated the LPOLESTR array with BSTRs instead.   This is a problem, because the caller is responsible for freeing the strings, and so it calls `CoTaskMemFree` on the BSTR, which is invalid and causes an immediate exception that I can see under a native debugger.

**Comment by Kr00l** [comment]
Thanks. I see what you mean.
However, it seems the VB6 IDE is expecting BSTRs. If I copy the content of StrPtr(StringsOutArray(nElemCount)) into lpString then the VB6 IDE crashes..

**Comment by WaynePhillipsEA** [comment]
It should look something like this:
```
        lpString = CoTaskMemAlloc(LenB(StringsOutArray(nElemCount)) + 2)
        CopyMemory ByVal lpString, ByVal StrPtr(StringsOutArray(nElemCount)), LenB(StringsOutArray(nElemCount)) + 2
        CopyMemory ByVal UnsignedAdd(pElems, nElemCount * 4), ByVal VarPtr(lpString), 4
```
 Tested, and no crash here.  Note change to LenB also.

**Comment by Kr00l** [comment]
My overlook was (in my first attempt) to not change `ByVal lpString` into `ByVal VarPtr(lpString)` at the last CopyMemory.

I updated/fixed now as below and it works:
```
    pCaStringsOut.cElems = cElems
    pCaStringsOut.pElems = pElems
    For nElemCount = 0 To cElems - 1
        Buffer = StringsOutArray(nElemCount) & vbNullChar
        lpString = CoTaskMemAlloc(LenB(Buffer))
        CopyMemory ByVal lpString, ByVal StrPtr(Buffer), LenB(Buffer)
        CopyMemory ByVal UnsignedAdd(pElems, nElemCount * 4), ByVal VarPtr(lpString), 4
    Next nElemCount
```
Stupid VB6 IDE to give me no crash before in the old code.

Thanks!
