### ISSUE TITLE
CommonDialog wrong constant

### ISSUE THREAD

**Issue by NBechtloff** [Kr00l/VBCCR#27]
I think the constant FR_HIDEMATCHCASE  should be &H8000&
But its declared in CommonDialog.cls line 409:
Private Const FR_HIDEMATCHCASE As Long = &H8000

**Comment by Kr00l** [comment]
Thanks. I see. I can't fix it for VBCCR17.OCX as VB6 won't allow me to re-compile without breaking binary compatibility.
So I keep this issue open for future..

**Comment by NBechtloff** [comment]
I understand and the issue is easy to avoid.
I just wanted to point out, that using the wrong value can cause your IDE the hard crash.
Can you not edit the Type Library of the binary compatibility file - then VB6 will let you compile without problems?
Its practically still breaking binary compatibility - but what does this actually break?

**Comment by Kr00l** [comment]
How to edit ? Feel free to edit the latest VBCCR17.OCX and send me over.
Sounds good idea. Yeah, practically it's not a real compatibility break as having something non-working now work is not a break actually.

**Comment by ulises2k** [comment]
Why don't you edit the source code and recompile?
https://github.com/Kr00l/VBCCR/blob/b00ba8ba1120d77595dadeb4f25670dff053f5c0/Standard%20EXE%20Version/Builds/CommonDialog.cls#L409

**Comment by Kr00l** [comment]
> Why don't you edit the source code and recompile?
> 
> https://github.com/Kr00l/VBCCR/blob/b00ba8ba1120d77595dadeb4f25670dff053f5c0/Standard%20EXE%20Version/Builds/CommonDialog.cls#L409

I can't. VB6 does not allow me to do it. At least not with the option "Binary compatibility". But I need that option, else everyone need to re-register. It's like doing a VBCCR18.

**Comment by ulises2k** [comment]
I think that for the people who use "part of the code" for our projects, it would be good to fix this bug.

**Comment by Kr00l** [comment]
I tried with a hex editor. But I can't find the spot to fix. Any advise is appreciated..

**Comment by NBechtloff** [comment]
There is an old VB6 IDE Plugin from Matthew Curland that was included in his Book "Advanced Visual Basic 6: Power Techniques for Everyday Programs".
That can change the Binary Copmpatibility File. I just tried it - works like a charm.
@Kr00l: Should I send you the modified VBCCR17.OCX? And how?

**Comment by Kr00l** [comment]
@NBechtloff great thanks!! I added you access to this repro. So just rename your VBCCR17.OCX into TempCompat.bin here in this repro and I take it to re-compile new version.

**Comment by Kr00l** [comment]
Thanks for the upload @NBechtloff . It got now re-compiled to v61.

**Comment by Kr00l** [comment]
@NBechtloff in the VBFLXGRD16.OCX we have an issue https://github.com/Kr00l/VBFLXGRD/issues/10 that the CompareText event arguments Text1 and Text2 should be As String instead of As Long. Could you please here once again help to modify the type lib so I can re-compile VBFLXGRD16.OCX ? I consider this bug as not a "practical compatibility" break as most of the users do not use this event. So a change here would certainly be without any noise.

**Comment by DaveInCaz** [comment]
@NBechtloff  is Curland's program available (in a legit way) online somewhere?

**Comment by NBechtloff** [comment]
@DaveInCaz  Legit - I think you need to obtain a copy of the book.
The official Homepage is still online. You can also download the CD if you obtained a copy without the CD.
http://powervb.mvps.org/

Alternative is:
You can also use a tool like ResourceHacker (http://www.angusj.com) to extract the Typelib from the dll/ocx.
Then you just need tool that can edit a tlb file - sadly I know of none.
After the edit you can replace the typelib resource with you edited one.

**Comment by DaveInCaz** [comment]
Thanks @NBechtloff .  Probably decompiling the IDL with OLEView, modifying it, and then recompiling with midl may work.
