### ISSUE TITLE
auto scroll on richtext

### ISSUE THREAD

**Issue by rockygsm** [Kr00l/VBCCR#3]
Hello
You made great help to all of us.
i started to use ocx and control version noticed bug on richtext change event.
Normally i used original richtext ocx do this.
when textarea is bigger its auto scroll to last line.
with change event on richtext
`richtext.SelStart = richtext.hWnd`
also try this
`richtext.SelStart = richtext.hWndUserControl`

both seems not working. i try to debug on controls but seems taking much time so i am reporting to you may be you can find faster then me?

regards,

**Comment by Kr00l** [comment]
Hi.
Why do you set .hWnd to selStart? That does not make sense(?)

**Comment by rockygsm** [comment]
To make richtext goto last line auto scroll same thing work on official richtext ocx. 
any other way ?

**Comment by rockygsm** [comment]
after few hrs debugging i found this solve issue.. seems control and ocx both version not update focus after sendmsg.
`richtext.SelStart = richtext.hWnd
rctxt1.SetFocus`
