### ISSUE TITLE
TextBoxW doesn't get de referenced when hosted in another usercontrol

### ISSUE THREAD

**Issue by melanysoft** [Kr00l/VBCCR#4]
**TextBoxW** contained in another custom UserControl **doesn't de reference** when UC gets terminated. In these cases when the form gets unloaded, TextBoxW doesn't terminate with it. Instead it lives until the end of application producing crashes (protected memory read) on the exit.

It happens when the **TextBoxW** control looses focus **by clicking** on certain type of controls (MSHFlexGrid, MSFlexGrid,...) on the same form. It doesn't happen if the focus is lost by tabbing or using other keyboard methods.

To investigate the code I've made a project group containing VBCCR16.vbp and a small exe (Crash.vbp) containing a simple **UserControl** having a **PictureBox** with **TextBoxW** on it. 

The main form **Crash.frm** contains **MSHFlexGrid**, **CommandButton** and a **UserControl** on it.
I made some changes so that TextBoxW shows its **Reference Counter** on request.

These are the steps to reproduce the problem:

1. When TextBoxW (on the UserControl) gets the focus there are **8** references to it.
2. When the focus is lost **by clicking** on the forms CommandButton number of references drops to **5**.
3. When the focus is lost **by clicking** on the forms MSHFlexGrid number of references drops to **6**.
4. When the focus is lost **by presing** TAB landing on either the CommandButton or MSHFlexGrid number of references drops to **5**.

When number of references is **6**, the TextBoxW doesn't terminate on form unload, but strangely, both the UserControl containing it and the Form does. That makes me think that it somehow holds the reference to itself. 

This doesn't happen when **TextBoxW** is hosted directly on the form or PictureBox placed on the form. In that case, clicking or tabbing to MSHFlexGrid drops references to **5**.

Examining the  messages shows equal patterns in all cases of focus switching.

Do you have any clue of what could be the reason ? 

I can give you a project group I've made if this is of any interest to you.

BTW, the code you made is AMAZING !!! 
There are many difficult concepts and hacks I wasn't aware VB6 is capable of. I can only imagine the time and effort you've invested in it. Brilliant...

**Comment by Kr00l** [comment]
Thanks for reporting. Yes please put a demo project showing the bug. Is this happening with other controls than TextBoxW?

**Comment by melanysoft** [comment]
Thanks for replying. I've added the ComboBoxW to the test, and yes, it shares the problem.

Zipped Crash Project can be downloaded from [here](https://rd.melany.rs/temp/labs/vbccr/Crash_Project.zip)

Content:
=======
a.) Folder **ActiveX Control Version** containing last VBCCR-master, adjusted with few lines of code to support the test. There are lot's of Debug.Print commands (commented or not) that follow the execution path too.
b.) Folder "Crash" containing the aaCrash.vbg that shold be opened in the IDE. There are also compiled versions Crash.exe and VBCCR16.ocx that reproduce the problem.

Testing:
=======
1. Run the .vbg in IDE or Crash.exe
2. Click on the *TxtW* in the UC. The reference counters will show 8 for TextBoxW and 6 for the UC
3. Click on any other control except the grids and the references will show 5,5
4. Click back to TxtW or CmbW. The references are 8,6
5. Click on the grids, references show 6,5

Try the same with the *Form TextW* , references are 5,5 after loosing focus always.

Closing the form with the 6,5 reference state crashes the program (some Windows versions suppress the message, but it will be recorded in the EventViewer).

I hope this is clear enough. Please feel free to ask for more info.

**Comment by melanysoft** [comment]
Uh, sorry, I've updated the archive. Please [download](https://rd.melany.rs/temp/labs/vbccr/Crash_Project.zip) it again.

**Comment by Kr00l** [comment]
I might have found the solution:

the cause is in DeactivateIPAO in VTableHandle.bas.
Set PropOleObject = VTableIPAOData.OriginalIOleIPAO
Set PropOleInPlaceActiveObject = Nothing 'VTableIPAOData.OriginalIOleIPAO

So instead of Set PropOleInPlaceActiveObject  = VTableIPAOData.OriginalIOleIPAO it is being set to Nothing.
I have the suspection that VB6 delegates IPAO on a form directly to the UC whereas when a UC is contained inside another UC it's delegated to the host UC (or outer UC)
I think it is a better attempt to set the ActiveObject then to Nothing. Because the next control in focus will anyhow set itself to be the new ActiveObject.

I await your comments for approval before I roll this out for update. Thanks

**Comment by melanysoft** [comment]
You're the master !  :)

The solution works as you suspected. The Crash Project shows correct reference counting, and the "real program" doesn't crash at the exit any more.

I don't see any problems when using controls directly on the form too. 

Should this be the final solution, or should I look for a way to detect when the control has a "form" as its container or is it the UC, to set the PropOleInPlaceActiveObject appropriately ?

**Comment by Kr00l** [comment]
No, that would be the final version. I will soon roll out the fix.

**Comment by melanysoft** [comment]
Ok. I'm glad you have found the solution. Thank you a lot.
