### ISSUE TITLE
Double Click "Jump to source"

### ISSUE THREAD

**Issue by NBechtloff** [Kr00l/VBCCR#7]
If a CommandButtonW is placed on another UserControl and that Control is compiled into an ocx the Double Click "Jump to source" feature does not work on the host control in the IDE. This seems to only be a problem if the CommandButtonW style is set to graphical.
I found this in WindowProcControl line 2012:
Case WM_LBUTTONDBLCLK
        If (GetWindowLong(hWnd, GWL_STYLE) And BS_OWNERDRAW) = BS_OWNERDRAW Then
            ' Buttons having the BS_OWNERDRAW style will not respond to double click as normal buttons do.
            ' Thus the default window procedure of the button will be called with WM_LBUTTONDOWN instead of the actual WM_LBUTTONDBLCLK.
            WindowProcControl = ComCtlsDefaultProc(hWnd, WM_LBUTTONDOWN, wParam, lParam)
            Exit Function
        End If

So if the button is graphical its window style gets the BS_OWNERDRAW set and it swallow the double click events the IDE needs?

Regards,

**Comment by Kr00l** [comment]
An additional condition with "And CommandButtonTopDesignMode = False" might fix it. So in IDE design mode it would get WM_LBUTTONDBLCLK and for IDE run mode or exe it would replace to WM_LBUTTONDOWN.

**Comment by NBechtloff** [comment]
I tried to analyze the problem further. It seems the relevant message for the designers "Jump to source" is WM_MOUSEACTIVATE. There already is a check for CommandButtonTopDesignMode = False in the WindowProcControl.
BUT for reasons beyond my comprehension the GetTopUserControl(Me).Ambient.UserMode call in UserControl_ReadProperties reports the wrong value (i.e. false). If i make the same assignment (CommandButtonTopDesignMode = Not GetTopUserControl(Me).Ambient.UserMode) in UserControl_Show again everything works just fine!
Now I dont know if that has any consequences for the compiled application. I feel a little bit unwary. Especially because I do not understand completely why this is working for the TextBoxW.

**Comment by Kr00l** [comment]
GetTopUserControl(Me).Ambient.UserMode call in UserControl_ReadProperties can only be flawed when your outer (host) UserControl do something stupid within UserControl_Initialize, because then the inner (child) UserControls may fire ReadProperties when in fact it's too early. So are you inzeracting with the childs within the host's UserControl_Initialize?

**Comment by NBechtloff** [comment]
You are correct. I am stupid.
Of course I interact with the child in the host's UserControl_Initialize.
Thanks a lot for your help, I would have never found that.
